[project]
name = "coding_finance"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "phil71x", email = "phil71x@live.com"},
]
dependencies = [
    "numpy==1.26.0",
    "numpy-financial",
    "pandas==2.1.1",
    "python-dateutil==2.8.2",
    "pytz==2023.3.post1",
    "six==1.16.0",
    "tzdata==2023.3",
    "matplotlib",
    "beautifulsoup4",
    "statsmodels",
    "yfinance",
]
requires-python = "==3.9.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
